apiVersion: v1
kind: Service
metadata:
  name: notification-service-api
spec:
  selector:
    app: notification-service-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
